config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get 'home/about' => 'home#about'
    devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :users,only: [:show,:index,:edit,:update] do
  	member do
      get :following, :followers
    end
  end
  get '/search' => 'search#search', as: 'search'

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
       favorites.where(user_id: user.id).exists?
    end
    has_many :book_comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_book, only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
      flash[:danger] = @book.errors.full_messages
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
      if current_user.id != @book.user_id
      redirect_to books_path
      end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def ensure_correct_book
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<td>
  <%= link_to(book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
  <% end %>
</td>
<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
<td><%= book.body %></td>
<!-- いいね機能 -->
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
      <%#= fa_icon "heart", text: "#{book.favorites.count}", style: "color: red;" %>
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
      <%#= fa_icon "heart-o", text: "#{book.favorites.count}", style: "color: red;" %>
      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_comment.html.erb
<% book_comments.each do |book_comment| %> <!-- コメント一覧 -->
  <tr>
    <td>
      <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
        <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_book_comments_path(book_comment), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>

app/views/books/_detail.html.erb
<td><%= link_to(book.user) do %>
  <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %><br>
  <%= book.user.name %>
  <% end %>
</td>
<td><%= link_to book.title, book %></td>
<td><%= book.body %></td>
<!-- いいね機能 -->
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

<% if book.user == current_user %>
  <td><%= link_to 'Edit', edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
  <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{book.id}"%></td>
<% end %>

app/views/books/_index.html.erb
 <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr class="book_<%= book.id %>">
        <%= render '/books/book', book: book %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>

	<div class="error">
		<% if book.errors.any? %>
			<%= pluralize(book.errors.count, "error") %><span>prohibited this book from being saved:</span>

			<ul>
				<% book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>

			<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>

		<%= link_to "Show", @book, class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>

    <%= render 'index', books: @books%>

	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>
		<h2>New book</h2>
		<%= render 'newform', book: @new_book %>
	</div>

  <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table class='table'>
      <tr class="book_<%= @book.id %>">
        <%= render 'detail', book: @book %>
      </tr>
    </table>

    <table class="show-tb comment_<%= @book.id %>">
      <%= render 'comment', book_comments: @book.book_comments %>
    </table>
        <div class="comment-form">
          <%= form_with(model: [@book, @book_comment], url: book_book_comments_path(@book) ) do |f| %>
            <div class="form-group row">
              <%= f.text_area :comment, size: "90x5" %>
              <%= f.submit "送信"%>
            </div>
          <% end %>
        </div>

  </div>
</div>