config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get 'home/about' => 'home#about'
    devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :users,only: [:show,:index,:edit,:update] do
  	member do
      get :following, :followers
    end
  end
  get '/search' => 'search#search', as: 'search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
       favorites.where(user_id: user.id).exists?
    end
    has_many :book_comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow,class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

    include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :postcode, :prefecture_code, :address_city, :address_street])
    #sign_upの際にnameのデータ操作を許。追加したカラム。

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_book, only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
      flash[:danger] = @book.errors.full_messages
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
      if current_user.id != @book.user_id
      redirect_to books_path
      end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def ensure_correct_book
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
        def create
            @book = Book.find(params[:book_id])
            favorite = current_user.favorites.new(book_id: @book.id)
            favorite.save
        end
        def destroy
            @book = Book.find(params[:book_id])
            favorite = current_user.favorites.find_by(book_id: @book.id)
            favorite.destroy
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 before_action :authenticate_user!, except: [:top, :about]

  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @book = Book.new

    if params[:genre] == "user"
      if params[:direction] == "完全一致"
        @users = User.where(name: "#{params[:q]}")
      elsif params[:direction] == "前方一致"
        @users = User.where('name LIKE ?', "#{params[:q]}%")
      elsif params[:direction] == "後方一致"
        @users = User.where('name LIKE ?', "%#{params[:q]}")
      elsif params[:direction] == "部分一致"
        @users = User.where('name LIKE ?', "%#{params[:q]}%")
      end

    elsif params[:genre] == "book"
      if params[:direction] == "完全一致"
        @books = Book.where(title: "#{params[:q]}", body: "#{params[:q]}")
      elsif params[:direction] == "前方一致"
        @books = Book.where('title LIKE ? OR body LIKE ?', "#{params[:q]}%", "#{params[:q]}%")
      elsif params[:direction] == "後方一致"
        @books = Book.where('title LIKE ? OR body LIKE ?', "%#{params[:q]}", "#{params[:q]}%")
      elsif params[:direction] == "部分一致"
        @books = Book.where('title LIKE ? OR body LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :baria_user, only: [ :update]

  def show
  	@user = User.find(params[:id])
    p @user.latitude
    p @user.longitude
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_searchform.html.erb
<%= form_with url: search_path, method: :get, local: true do |f| %>
  <%= f.text_field :q, placeholder: "検索ワードを入力" %>
  <%= f.select :genre, [["user", "user"], ["book", "book"]] %>
  <%= f.select :direction, [["完全一致","完全一致"], ["前方一致", "前方一致"], ["後方一致", "後方一致"], ["部分一致","部分一致"]] %>
  <%= f.submit "検索" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
                <li><%= link_to  "  Home", user_path(current_user.id), class: "home glyphicon glyphicon-home" %></li>
                <li><%= link_to  "  Users", users_path, class: "users glyphicon glyphicon-user" %></li>
                <li><%= link_to  "  Books", books_path, class: "books glyphicon glyphicon-book" %></li>
                <li><%= link_to  "  logout", destroy_user_session_path, class: "logout glyphicon glyphicon-log-out", method: :delete %></li>
              <% else %>
                <li><%= link_to  "  Home", root_path, class: "home glyphicon glyphicon-home" %></li>
                <li><%= link_to  "  About", home_about_path, class: "about glyphicon glyphicon-link" %></li>
                <li><%= link_to "  Sign Up", new_user_registration_path, class: "sign_up glyphicon glyphicon-edit" %></li>
                <li><%= link_to "  login", new_user_session_path, class: "sign_in glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p>

      <!--検索フォーム-->
      <% if user_signed_in? %>
        <div class="container">
          <%= render 'layouts/searchform' %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>